name = "Zexade"
author = "marte26"
version = "2.0.1+1.21.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "947608af5e1a822747f6658a29b596c00bce040d3d2b2f33c7455b4b27ac8ad6"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"
