name = "Zexade"
author = "marte26"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "69aa00b9b12fb28a33dc0fd9f71be6fd0cf3ae7d0043145480dafbfc6cb9191d"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
